apiVersion: v1
kind: ReplicationController
metadata:
    name: hbase1
spec:
  replicas: 1
  selector:
    k8s-app: hbase1
  template:
    metadata:
      labels:
        k8s-app: hbase1
    spec:
      containers:
        - name: hbase-node
          image: index.caicloud.io/caicloud/hbase:distributed
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
            name: api
          - containerPort: 8085
            name: web
          - containerPort: 9090
            name: thriftapi
          - containerPort: 9095
            name: thriftwebui
          - containerPort: 2181
            name: zookeeper
          - containerPort: 16010
            name: hbase-master
---
apiVersion: v1
kind: Service
metadata:
  name: hbase1
spec:
  ports:
    - name: api
      port: 8080
      targetPort: 8080
    - name: web
      port: 8085
      targetPort: 8085
    - name: thriftapi
      port: 9090
      targetPort: 9090
    - name: zookeeper
      port: 2181
      targetPort: 2181
    - name: thriftwebui
      port: 9095
      targetPort: 9095
    - name: hbase-master
      port: 16010
      targetPort: 16010
  selector:
    k8s-app: hbase1
